name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * *"

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          New-Item -ItemType Directory -Force -Path build/assets

      - name: Build Stable
        run: |
          python run.py
          $version = Get-Content build/release/Chrome/version.txt
          echo "STABLE_VERSION=$version" >> $env:GITHUB_ENV
          $date = Get-Date -Format 'yyyy-MM-dd'
          echo "BUILD_DATE=$date" >> $env:GITHUB_ENV
          $zipName = "Chrome++_stable_$date.zip"
          Compress-Archive -Path build/release/Chrome -DestinationPath "build/assets/$zipName"

      - name: Build Beta
        run: |
          python run_beta.py
          $version = Get-Content build/release/Chrome/version.txt
          echo "BETA_VERSION=$version" >> $env:GITHUB_ENV
          $date = Get-Date -Format 'yyyy-MM-dd'
          $zipName = "Chrome++_beta_$date.zip"
          Compress-Archive -Path build/release/Chrome -DestinationPath "build/assets/$zipName"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Chrome-Portable-Builds
          path: build/assets/*.zip
          retention-days: 15

      - name: Create Release
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BUILD_DATE }}
          name: Chrome++ Release ${{ env.BUILD_DATE }}
          body: |
            Chrome++ 构建版本 ${{ env.BUILD_DATE }}
            
            Stable 版本: ${{ env.STABLE_VERSION }}
            Beta 版本: ${{ env.BETA_VERSION }}
          files: build/assets/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Older Releases
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
